export const storeUserInfo = 'storeUserInfo'

export const SET_REQUEST_END = 'SET_REQUEST_END'

export const REMOVE_STORAGE_USER_INFO = 'REMOVE_STORAGE_USER_INFO'

export const SET_PLAY_LIST = 'SET_PLAY_LIST'

export const SET_SONG_SEQUENCE = 'SET_SONG_SEQUENCE'

export const SET_CURRENT_SONG = 'SET_CURRENT_SONG'

export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'

export const SET_PLAYING_STATE = 'SET_PLAYING_STATE'

export const SET_FULL_SCREEN = 'SET_FULL_SCREEN'

export const SET_SONG_READY = 'SET_SONG_READY'

export const SET_PLAYER_MODE = 'SET_PLAYER_MODE'